from tkinter import *
def button(num):
    global ch
    c=entre.get()
    ch=str(c) + str(num)
    entre.delete(0,END)
    entre.insert(0,ch)

def resultat():
    result=eval(ch)
    entre.delete(0,END)
    entre.insert(0, result)


def supprime():
    entre.delete(0,END)

fen=Tk()
fen.title('Standard Calculator')
entre=Entry(fen,width=50,borderwidth=5)
entre.grid(row=0,column=0,columnspan=4)
#can=Canvas(fen,height=400,width=300,bg='black')
#can.pack()
boutton11=Button(fen,text='7',padx=40,pady=20,command= lambda :button(7),font='Times 12')
boutton11.grid(row=1,column=0)
boutton12=Button(fen,text='8',padx=40,pady=20,command= lambda :button(8),font='Times 12')
boutton12.grid(row=1,column=1)
boutton13=Button(fen,text='9',padx=40,pady=20,command= lambda :button(9),font='Times 12')
boutton13.grid(row=1,column=2)
boutton14=Button(fen,text='/',padx=40,pady=20,command= lambda :button('/'),font='Times 12')
boutton14.grid(row=1,column=3)
boutton15=Button(fen,text='4',padx=40,pady=20,command= lambda :button(4),font='Times 12')
boutton15.grid(row=2,column=0)
boutton16=Button(fen,text='5',padx=40,pady=20,command= lambda :button(5),font='Times 12')
boutton16.grid(row=2,column=1)
boutton17=Button(fen,text='6',padx=40,pady=20,command= lambda :button(6),font='Times 12')
boutton17.grid(row=2,column=2)
boutton18=Button(fen,text='*',padx=40,pady=20,command= lambda :button('*'),font='Times 12')
boutton18.grid(row=2,column=3)
boutton19=Button(fen,text='1',padx=40,pady=20,command= lambda :button(1),font='Times 12')
boutton19.grid(row=3,column=0)
boutton21=Button(fen,text='2',padx=40,pady=20,command= lambda :button(2),font='Times 12')
boutton21.grid(row=3,column=1)
boutton22=Button(fen,text='3',padx=40,pady=20,command= lambda :button(3),font='Times 12')
boutton22.grid(row=3,column=2)
boutton23=Button(fen,text='+',padx=38.45,pady=20,command= lambda :button('+'),font='Times 12')
boutton23.grid(row=3,column=3)
boutton24=Button(fen,text='0',padx=40,pady=20,command= lambda :button(0),font='Times 12')
boutton24.grid(row=4,column=0)
boutton25=Button(fen,text='.',padx=41,pady=20,command= lambda :button('.'),font='Times 12')
boutton25.grid(row=4,column=1)
boutton26=Button(fen,text='=',padx=39,pady=20,command=resultat,font='Times 12')
boutton26.grid(row=4,column=2)
boutton27=Button(fen,text='-',padx=40,pady=20,command= lambda :button('-'),font='Times 12')
boutton27.grid(row=4,column=3)
boutton28=Button(fen,text='Entr',padx=78,pady=20,command=resultat,font='Times 12')
boutton28.grid(row=5,column=0,columnspan=2)
boutton28=Button(fen,text='clear all',padx=70,pady=20,command=supprime,font='Times 12')
boutton28.grid(row=5,column=2,columnspan=2)

fen.mainloop()